#批量添加和修改、删除front matter配置文件

# 需要批量处理的路径，docs文件夹内的文件夹  (数组。映射路径：docs/arr[0]/arr[1] ... )
path:
  - docs # 第一个成员必须是docs
  - 01.前端
  - 40.学习笔记

# 要删除的字段 (数组)
delete:  
  - test
  # - tags

 # 要添加、修改front matter的数据 （front matter中没有的数据则添加，已有的数据则覆盖）
data:
  # test: 阮一峰