## 利用GitHub Actions每天定时给百度推送链接，提高收录率 ##

name: baiduPush

# 两种触发方式：一、push代码，二、每天国际标准时间23点（北京时间+8即早上7点）运行
on:
  push:
  schedule:
    - cron: '0 23 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
      - name: 'Run baiduPush.sh' # 步骤二，执行sh命令文件
        run: bash ./baiduPush.sh # 注意，运行目录和文件是同一目录